### ISSUE TITLE
[Spike] Install Kubernetes in test enviroment and go through tutorial

### ISSUE THREAD

**Issue by SubZero12556** [49thSecurityDivision/lab-documentation#7]
author is @SubZero12556 

**Describe what prompted this request**
Kubernetes will be implemented in the lab. I plan to be the point of contact for information about Kubernetes.

**Describe the solution you'd like**
Complete tutorial for Kubernetes from https://kubernetes.io/docs/tutorials/kubernetes-basics/
**Who is the target user for this? **
Lab trolls and minions.
**Will it need to be maintained?** 
Yes, documentation will be updated as more about Kubernetes is learned.
**Who should have access?**
Lab trolls and minions.
**Are these docs testable? (not all documentation will be testable)**
Yes, include what I did to install Kubernetes as a general knowledge hub of how to use it.
**Will there be sensitive information in these docs?**
No.

**Comment by elreydetoda** [comment]
We talked about this, and you are going to hold off till winter break to do this. Till then you should work on vault.
